- {'M': 152710, 'N': 2048, 'K': 512, 'rowMajorA': 'T', 'rowMajorB': 'N', 'bias': 2048}
- {'M': 64896, 'N': 2048, 'K': 512, 'rowMajorA': 'T', 'rowMajorB': 'N', 'bias': 2048}
- {'M': 16384, 'N': 128, 'K': 2304, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 6, 'N': 384, 'K': 1536, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 6, 'N': 3072, 'K': 768, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 16384, 'N': 2, 'K': 2304, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 6144, 'N': 384, 'K': 384, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 2048, 'N': 131072, 'K': 16384, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 462, 'N': 768, 'K': 384, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 462, 'N': 4096, 'K': 384, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 16384, 'N': 32768, 'K': 2304, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 462, 'N': 1472, 'K': 384, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 6144, 'N': 384, 'K': 3072, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 6144, 'N': 1536, 'K': 384, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 16384, 'N': 128, 'K': 13312, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 6, 'N': 3072, 'K': 1536, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 2048, 'N': 65536, 'K': 16384, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 1536, 'N': 768, 'K': 768, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 462, 'N': 768, 'K': 768, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 462, 'N': 4096, 'K': 768, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 2048, 'N': 8192, 'K': 16384, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 462, 'N': 1472, 'K': 768, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 1536, 'N': 768, 'K': 6144, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 1536, 'N': 3072, 'K': 768, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 16384, 'N': 8, 'K': 13312, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 6, 'N': 3072, 'K': 3072, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 384, 'N': 1536, 'K': 1536, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 16384, 'N': 4096, 'K': 13312, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 462, 'N': 768, 'K': 1536, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 462, 'N': 4096, 'K': 1536, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 462, 'N': 1472, 'K': 1536, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 384, 'N': 1536, 'K': 12288, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 384, 'N': 6144, 'K': 1536, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 2048, 'N': 32768, 'K': 16384, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 96, 'N': 1536, 'K': 1536, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 96, 'N': 1536, 'K': 12288, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 96, 'N': 6144, 'K': 1536, 'rowMajorA': 'T', 'rowMajorB': 'N'}
