- {'M': 2048, 'N': 152710, 'K': 512, 'rowMajorA': 'T', 'rowMajorB': 'N', 'bias': 2048}
- {'M': 2048, 'N': 64896, 'K': 512, 'rowMajorA': 'T', 'rowMajorB': 'N', 'bias': 2048}
- {'M': 128, 'N': 16384, 'K': 2304, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 384, 'N': 6, 'K': 1536, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 3072, 'N': 6, 'K': 768, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 2, 'N': 16384, 'K': 2304, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 384, 'N': 6144, 'K': 384, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 131072, 'N': 2048, 'K': 16384, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 768, 'N': 462, 'K': 384, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 4096, 'N': 462, 'K': 384, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 32768, 'N': 16384, 'K': 2304, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 1472, 'N': 462, 'K': 384, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 384, 'N': 6144, 'K': 3072, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 1536, 'N': 6144, 'K': 384, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 128, 'N': 16384, 'K': 13312, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 3072, 'N': 6, 'K': 1536, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 65536, 'N': 2048, 'K': 16384, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 768, 'N': 1536, 'K': 768, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 768, 'N': 462, 'K': 768, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 4096, 'N': 462, 'K': 768, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 8192, 'N': 2048, 'K': 16384, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 1472, 'N': 462, 'K': 768, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 768, 'N': 1536, 'K': 6144, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 3072, 'N': 1536, 'K': 768, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 8, 'N': 16384, 'K': 13312, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 3072, 'N': 6, 'K': 3072, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 1536, 'N': 384, 'K': 1536, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 4096, 'N': 16384, 'K': 13312, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 768, 'N': 462, 'K': 1536, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 4096, 'N': 462, 'K': 1536, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 1472, 'N': 462, 'K': 1536, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 1536, 'N': 384, 'K': 12288, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 6144, 'N': 384, 'K': 1536, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 32768, 'N': 2048, 'K': 16384, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 1536, 'N': 96, 'K': 1536, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 1536, 'N': 96, 'K': 12288, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 6144, 'N': 96, 'K': 1536, 'rowMajorA': 'T', 'rowMajorB': 'N'}
