- {'M': 256, 'N': 256, 'K': 256, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 384, 'N': 384, 'K': 384, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 512, 'N': 512, 'K': 512, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 640, 'N': 640, 'K': 640, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 768, 'N': 768, 'K': 768, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 896, 'N': 896, 'K': 896, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 1024, 'N': 1024, 'K': 1024, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 1152, 'N': 1152, 'K': 1152, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 1280, 'N': 1280, 'K': 1280, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 1408, 'N': 1408, 'K': 1408, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 1536, 'N': 1536, 'K': 1536, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 1664, 'N': 1664, 'K': 1664, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 1792, 'N': 1792, 'K': 1792, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 1920, 'N': 1920, 'K': 1920, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 2048, 'N': 2048, 'K': 2048, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 2176, 'N': 2176, 'K': 2176, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 2304, 'N': 2304, 'K': 2304, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 2432, 'N': 2432, 'K': 2432, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 2560, 'N': 2560, 'K': 2560, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 2688, 'N': 2688, 'K': 2688, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 2816, 'N': 2816, 'K': 2816, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 2944, 'N': 2944, 'K': 2944, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 3072, 'N': 3072, 'K': 3072, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 3200, 'N': 3200, 'K': 3200, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 3328, 'N': 3328, 'K': 3328, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 3456, 'N': 3456, 'K': 3456, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 3584, 'N': 3584, 'K': 3584, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 3712, 'N': 3712, 'K': 3712, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 3840, 'N': 3840, 'K': 3840, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 3968, 'N': 3968, 'K': 3968, 'rowMajorA': 'T', 'rowMajorB': 'N'}
- {'M': 4096, 'N': 4096, 'K': 4096, 'rowMajorA': 'T', 'rowMajorB': 'N'}
